networks:
  app-tier:
    driver: bridge
services:
  api:
    image: tahnamao-api
    build: .
    networks:
      - app-tier
    ports:
      - "3000:3000"

  web-cli:
    image: tahnamao-api
    networks:
      - app-tier
    command: sh

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "3306"

    environment:
      MYSQL_DATABASE: tahnamao_test
      MYSQL_USER: root
      MYSQL_PASSWORD: gabilimajk12
      MYSQL_ROOT_HOST: "%"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  backend:
    depends_on:
      - db
    build: .
