version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    networks:
      - app-tier
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  web-cli:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    networks:
      - app-tier
    command: sh

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: tahnamao_test
      MYSQL_PASSWORD: gabilimajk12
      MYSQL_ROOT_HOST: "%"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
